name       : xfce4-dev-tools
version    : 4.18.0
release    : 1
source     :
    - https://archive.xfce.org/src/xfce/xfce4-dev-tools/4.18/xfce4-dev-tools-4.18.0.tar.bz2 : eedb4fc955f0e3459c46864ff98579295db2b900743e0ff69cad5970ba76be37
license    : GPL-2.0-or-later
component  : desktop.xfce.core
summary    : The Xfce development tools are a collection of tools and macros for Xfce developers.
description: |
    The Xfce development tools are a collection of tools and macros for Xfce developers.
builddeps  :
    - pkgconfig(glib-2.0)
    - gtk-doc
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
